name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update waka-time stats
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3
        with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SHOW_LANGUAGE: FALSE
            SHOW_OS: FALSE
            SHOW_PROJECTS: FALSE
            SHOW_TIMEZONE: FALSE
            SHOW_EDITORS: FALSE
            SHOW_LANGUAGE_PER_REPO: FALSE
            SHOW_SHORT_INFO: FALSE
            SHOW_LOC_CHART: FALSE
          
              
